import os
import json
from litellm import completion
from db.lightrag_manager import LightRAGManager

class LargeLLMExtractor:
    """
    Stage 4 LLM (70B+ Model).
    Responsible for deep-dive code analysis and strict JSON Extraction.
    Uses LiteLLM to dynamically switch between self-hosted DGX clusters and Cloud Models (Gemini).
    """
    def __init__(self, db_manager: LightRAGManager):
        # Allow override via environment variables, default to our local DGX 70B Host
        self.model = os.environ.get("EXTRACTOR_MODEL", "openai/meta-llama/Meta-Llama-3-70B-Instruct")
        self.api_base = os.environ.get("EXTRACTOR_API_BASE", "http://gx10:8080/v1")
        self.api_key = os.environ.get("EXTRACTOR_API_KEY", "dgx-dummy-key")
        self.db = db_manager
        
    def extract_rule(self, pr_comment: str, modified_ast_code: str) -> dict:
        """
        Extracts negative constraints / architectural choices generated by reviewers.
        """
        system_prompt = (
            "You are an expert AI Architect extracting coding rules into strict JSON. "
            "Your goal is to parse reviewer feedback and isolate what the Copilot did WRONG. "
            "Output ONLY valid JSON following this schema: "
            "{'rule_id': 'uuid', 'metadata': {'status': 'active'}, 'content': {'title': '...', 'description': '...', 'enforcement_prompt': '...'}}"
        )
        
        user_prompt = f\"\"\"
        <REVIEW_DATA>
        {pr_comment}
        </REVIEW_DATA>
        
        <CODE_DIFF>
        {modified_ast_code}
        </CODE_DIFF>
        \"\"\"
        
        try:
            response = completion(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                api_base=self.api_base,
                api_key=self.api_key,
                temperature=0.1
            )
            raw_content = response.choices[0].message.content.strip()
            
            # Remove markdown JSON wrappers if the model leaked them
            if raw_content.startswith("```json"):
                raw_content = raw_content.replace("```json", "").replace("```", "").strip()
                
            rule_dict = json.loads(raw_content)
            
            # Post-Process: Automatically store the heavy-lifting extraction into the ChromaDB CodeRAG Receiver
            self.db.store_rule(rule_dict)
            return rule_dict
            
        except Exception as e:
            print(f"[Extractor Error]: {e}")
            return None
