/**
 * Server-side proxy: forwards browser fetches to the FastAPI backend with the
 * API auth token attached. The token only lives on the Next.js server — never
 * shipped in the client JS bundle.
 *
 * Resolution for the bearer token (highest priority first):
 *   1. API_AUTH_TOKEN env var (operator override).
 *   2. /app/data/.api_token (auto-generated by the backend on first start;
 *      mounted into this container as a read-only volume).
 *   3. Empty — proxy still forwards but without auth (matches backend dev
 *      mode where API_AUTH_TOKEN is unset).
 *
 * The token is process-cached for performance. On a 401 from the backend the
 * proxy invalidates the cache, re-reads the token file, and retries once —
 * this lets the operator rotate the token by `rm data/.api_token` without
 * also restarting the web-ui container.
 */

import { NextRequest, NextResponse } from "next/server";
import { promises as fs } from "node:fs";
import path from "node:path";

const BACKEND_URL =
  process.env.BACKEND_INTERNAL_URL ||
  process.env.NEXT_PUBLIC_API_URL ||
  "http://127.0.0.1:8923";

/**
 * Candidate paths for the auto-generated token file, in priority order.
 *
 * - In Docker: API_AUTH_TOKEN_FILE points at /backend-data/.api_token (the
 *   read-only volume mount), so the rest of this list is irrelevant.
 * - In local `npm run dev` from web-ui/: cwd is web-ui/, the backend runs
 *   from backend/ and writes backend/data/.api_token. The walk-up search
 *   below finds it without the operator having to set anything.
 */
function candidateTokenPaths(): string[] {
  if (process.env.API_AUTH_TOKEN_FILE) return [process.env.API_AUTH_TOKEN_FILE];
  const candidates: string[] = [];
  let dir = process.cwd();
  // Walk up to the filesystem root, checking both `data/` and
  // `backend/data/` at each level.
  while (true) {
    candidates.push(path.join(dir, "data", ".api_token"));
    candidates.push(path.join(dir, "backend", "data", ".api_token"));
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return candidates;
}

let cachedToken: string | null = null;

async function readTokenFromSource(): Promise<string> {
  if (process.env.API_AUTH_TOKEN) return process.env.API_AUTH_TOKEN;
  for (const p of candidateTokenPaths()) {
    try {
      const content = await fs.readFile(p, "utf-8");
      const trimmed = content.trim();
      if (trimmed) return trimmed;
    } catch {
      // Try the next candidate.
    }
  }
  return "";
}

async function resolveToken(forceRefresh = false): Promise<string> {
  if (!forceRefresh && cachedToken !== null) return cachedToken;
  cachedToken = await readTokenFromSource();
  return cachedToken;
}

const HOP_BY_HOP = new Set([
  "connection",
  "keep-alive",
  "proxy-authenticate",
  "proxy-authorization",
  "te",
  "trailers",
  "transfer-encoding",
  "upgrade",
  "host",
  "content-length",
]);

// Pass-through note: SSE responses (text/event-stream) require the upstream
// Cache-Control: no-cache and X-Accel-Buffering: no headers to flow through
// untouched. We don't add or rewrite cache-control on responses; HOP_BY_HOP
// excludes neither header. Verified by manual smoke test in dev.
async function executeUpstream(
  targetUrl: string,
  method: string,
  inboundHeaders: Headers,
  body: ArrayBuffer | null,
  token: string,
): Promise<Response> {
  const headers = new Headers();
  inboundHeaders.forEach((value, key) => {
    if (!HOP_BY_HOP.has(key.toLowerCase())) headers.set(key, value);
  });
  if (token) headers.set("Authorization", `Bearer ${token}`);
  const init: RequestInit = {
    method,
    headers,
    redirect: "manual",
  };
  if (body !== null) init.body = body;
  return fetch(targetUrl, init);
}

async function forward(
  req: NextRequest,
  ctx: { params: Promise<{ path: string[] }> }
): Promise<Response> {
  const { path: segments } = await ctx.params;
  const search = req.nextUrl.search;
  const targetUrl = `${BACKEND_URL.replace(/\/$/, "")}/${segments.join("/")}${search}`;

  const body =
    req.method !== "GET" && req.method !== "HEAD" ? await req.arrayBuffer() : null;

  let token = await resolveToken();
  let upstream = await executeUpstream(targetUrl, req.method, req.headers, body, token);

  // If the backend rejected the cached token, the operator may have rotated
  // it. Invalidate the cache, re-read the source of truth, and retry once.
  if (upstream.status === 401) {
    const refreshed = await resolveToken(true);
    if (refreshed && refreshed !== token) {
      token = refreshed;
      upstream = await executeUpstream(targetUrl, req.method, req.headers, body, token);
    }
  }

  const respHeaders = new Headers();
  upstream.headers.forEach((value, key) => {
    if (!HOP_BY_HOP.has(key.toLowerCase())) respHeaders.set(key, value);
  });
  return new NextResponse(upstream.body, {
    status: upstream.status,
    statusText: upstream.statusText,
    headers: respHeaders,
  });
}

export const GET = forward;
export const POST = forward;
export const PUT = forward;
export const PATCH = forward;
export const DELETE = forward;
