import json
from typing import List, NamedTuple


class _ParsedRule(NamedTuple):
    title: str
    context: str
    enforcement: str


def _parse_rule(raw: str) -> _ParsedRule:
    """Decomposes a raw ChromaDB rule string into its three semantic parts.

    Expected format:
      "Rule: <title> - Context: <context>. Enforce: <enforcement>"

    Both the context and enforcement sections are optional.
    """
    title = raw
    context = ""
    enforcement = ""

    if " - Context: " in raw:
        header, detail = raw.split(" - Context: ", 1)
        title = header.replace("Rule: ", "").replace("rule:", "").strip()
        if ". Enforce: " in detail:
            context, enforcement = detail.split(". Enforce: ", 1)
            context = context.strip()
            enforcement = enforcement.strip()
        else:
            context = detail.strip()

    return _ParsedRule(title=title, context=context, enforcement=enforcement)


class SkillSynthesizer:
    """
    Transforms extracted ChromaDB textual documents into universal LLM boundaries.
    """

    @staticmethod
    def generate_prompt(rules: List[str]) -> str:
        prompt = "You are an expert AI architect. You must strictly adhere to the following project-specific constraints:\n\n"
        for i, rule in enumerate(rules, 1):
            prompt += f"{i}. {rule}\n"
        return prompt.strip()

    @staticmethod
    def generate_skill_md(rules: List[str], repo: str) -> str:
        md = f"# Project Architecture Skills: {repo}\n\n"
        md += "This document outlines explicit functional constraints for this environment. Prioritize these mappings whenever modifying local architectural boundaries.\n\n"
        md += "## Structural Constraints\n"

        for raw in rules:
            parsed = _parse_rule(raw)
            md += f"- **{parsed.title}**\n"
            if parsed.context:
                md += f"  - *Context:* {parsed.context}\n"
            if parsed.enforcement:
                md += f"  - *Enforcement:* {parsed.enforcement}\n"
            if not parsed.context and not parsed.enforcement:
                # bare rule with no structured parts — show it as-is
                md += f"  - {raw}\n"

        return md.strip()

    @staticmethod
    def generate_cursorrules(rules: List[str], repo: str) -> str:
        """Generates a .cursorrules-compatible plain-text file.

        Each rule becomes one enforcement line, prefixed with its title.
        The format Cursor expects is a flat list of plain-text directives.
        """
        lines = [
            f"# Project rules for {repo}",
            "# Auto-generated by PR-Distiller. Do not edit manually.",
            "",
        ]

        for raw in rules:
            parsed = _parse_rule(raw)
            if parsed.enforcement:
                lines.append(f"{parsed.title}: {parsed.enforcement}")
            elif parsed.context:
                lines.append(f"{parsed.title}: {parsed.context}")
            else:
                lines.append(raw)

        return "\n".join(lines)

    @staticmethod
    def generate_claude_md(rules: List[str], repo: str) -> str:
        """Generates a CLAUDE.md-compatible markdown document.

        Each rule becomes an H2 section with Context and Enforcement sub-blocks,
        matching the structure Claude Code expects in CLAUDE.md files.
        """
        sections = [
            f"# CLAUDE.md — Coding Rules for {repo}",
            "",
            "These rules were extracted from PR reviews. Follow them strictly when modifying this codebase.",
            "",
        ]

        for raw in rules:
            parsed = _parse_rule(raw)
            sections.append(f"## {parsed.title}")
            sections.append("")
            if parsed.context:
                sections.append(f"**Context:** {parsed.context}")
                sections.append("")
            if parsed.enforcement:
                sections.append(f"**Enforce:** {parsed.enforcement}")
                sections.append("")
            if not parsed.context and not parsed.enforcement:
                sections.append(raw)
                sections.append("")

        return "\n".join(sections).rstrip()

    @staticmethod
    def generate_agent_schema(rules: List[str], target_arch: str) -> str:
        if target_arch == "anthropic":
            xml = "<tool_description>\n"
            xml += "  <tool_name>apply_project_constraints</tool_name>\n"
            xml += "  <description>Strict architectural constraints that must be followed during logic generations.</description>\n"
            xml += "  <rules>\n"
            for rule in rules:
                xml += f"    <rule>{rule}</rule>\n"
            xml += "  </rules>\n"
            xml += "</tool_description>"
            return xml
        else:
            schema = {
                "name": "apply_project_constraints",
                "description": "Strict architectural constraints that must be followed during logic generations.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "acknowledged_rules": {
                            "type": "array",
                            "items": {"type": "string"},
                            "description": "The engine must state it has parsed these boundaries."
                        }
                    },
                    "required": ["acknowledged_rules"]
                },
                "instructions": rules
            }
            return json.dumps(schema, indent=2)

    @classmethod
    def export(cls, rules: List[str], repo: str, format_type: str, target_arch: str = "openai") -> str:
        """Controller function matching UI requests to parsing topologies."""
        if not rules:
            return "No active rules found for this namespace. Distill and approve rules first."

        if format_type == "prompt":
            return cls.generate_prompt(rules)
        elif format_type == "skill":
            return cls.generate_skill_md(rules, repo)
        elif format_type == "agent":
            return cls.generate_agent_schema(rules, target_arch)
        elif format_type == "cursorrules":
            return cls.generate_cursorrules(rules, repo)
        elif format_type == "claude_md":
            return cls.generate_claude_md(rules, repo)

        return "Unknown format requested."
